#!/bin/sh

readonly tables=(arches packages{,_depend,_packagegroup,_provision} repos)

psql arch_rebuilds <<EOQ
    drop table if exists $(IFS=,; echo "${tables[*]}");
EOQ

ssh repos.archlinux.org pg_dump -O -x -h gudrun.archlinux.org -U archweb_update -d archweb \
    $(printf ' -t %s' ${tables[@]}) |
    psql arch_rebuilds
